version: '3.9'
services:
  sgx-revm:
    image: sgx-revm
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 7878:7878
    depends_on:
      aesmd:
        condition: service_started
    devices:
      - /dev/isgx
    working_dir: /sgx-revm
    volumes:
      - aesmd-socket:/var/run/aesmd
      - ./:/sgx-revm

  aesmd:
    image: fortanix/aesmd
    volumes:
      - aesmd-socket:/var/run/aesmd
    devices:
      - /dev/isgx

volumes:
  aesmd-socket:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "rw"